eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://host.docker.internal:8761/eureka}
okta:
  oauth2:
    issuer: https://dev-56301073.okta.com/oauth2/default
    audience: api://default
